### ISSUE TITLE
Talk Idea: Docker for Beginners 

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#31]
Kevin K has offered to talk about Docker and DevOps. Originally scheduled for SEP 2016, he had to postpone indefinitely.

**Comment by codetojoy** [comment]
Assigning to myself as a proxy for Kevin K.

**Comment by codetojoy** [comment]
Kevin K is looking for suggestions for topics in the Docker for Beginners talk:

_[aside from intro] most of the talk being an actual walkthrough and demonstration of Docker (and possibly Docker Compose). Since you guys already had one talk on this let me know if there are any specific points you would like me to cover._

**Comment by swhalley** [comment]
Possible topics were discussed here
https://github.com/peidevs/Event_Resources/issues/27

Going to close issue #27 since they are essentially duplicates

**Comment by jpatters** [comment]
I notice this got bumped. If you would still like it to happen and the original speaker isn't available, I'd be more than happy to do it.

**Comment by codetojoy** [comment]
Thanks, Jordan. Can we put you down for March, 2017? (That's the earliest opening... we've received a fabulous spike in speaker submissions)

**Comment by jpatters** [comment]
@codetojoy that works for me. Congrats on the full schedule!

**Comment by jpatters** [comment]
@codetojoy I'm going to prepare a second docker talk on docker-compose and the Dockerfile. People seemed to have a lot of questions about those specifically. I really wanted the first one to be more of an intro though. I can have it ready for whenever.

**Comment by codetojoy** [comment]
Closing this issue as Jordan has given 3 Docker talks (thanks!)
