### ISSUE TITLE
Talk Idea: AWS (Oct 13 2016)

### ISSUE THREAD

**Issue by jpatters** [peidevs/Event_Resources#32]
Navigating the Amazon Jungle (potential title?)
It can often be confusing.

I've got ~5 years experience working with a number of their various platforms so I'd be able to give this talk, but I won't be available until at least October.
If anyone is interested, comment which specific services you would be interested in or topics you would like covered. You can see a full list here https://aws.amazon.com/products/

**Comment by swhalley** [comment]
Talk in Slack, try and focus on 1-3 products aws offers and how to use them.  Too many and you may lose the new-to-aws-people [aka me]

seeing a simple push to prod/test may be good.

**Comment by jpatters** [comment]
I'm thinking the best place to start is EC2 (vps) and RDS (managed db). Probably the most immediately useful. Any objections?

**Comment by swhalley** [comment]
no objections

**Comment by evanepio** [comment]
Oct 2016
