### ISSUE TITLE
Talk Idea: monads

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#34]
In 2009, I gave a talk in STL on monads (from functional programming), using Haskell.

I could resuscitate that talk, or alternatively give a talk that motivates monads using Java or JavaScript.

I'd need at least 2 months notice.

**Comment by evanepio** [comment]
Where's my burrito emoji? Thumbs up will have to do.

**Comment by 2manyprojects2littletime** [comment]
_the monad talk comes back into view from the primordial fog of peidevs_
I've heard of the talk multiple times, but wasn't there to witness the original.  +100000
