### ISSUE TITLE
Talk Idea: Gradle

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#36]
I gave a talk on Gradle in spring 2012 (when we were really small). I could do it again if there is interest.

This would not cover the Android Studio stuff. If there is interest, I could research that but would need 2 months notice.

**Comment by 2manyprojects2littletime** [comment]
I am interested in the android studio stuff, but would like to see how it works in the degenerate case too.

**Comment by gauthierm** [comment]
I'm interested in the Android side of things.
