### ISSUE TITLE
Talk idea: TensorFlow

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#39]
I'm not sure I'm offering to give the talk, but I'm interested in learning more about Google's machine-learning libraries (TensorFlow).

If it is me, I would need 3-4 months notice.

**Comment by Qcode** [comment]
I recently finished a first draft of a 4000 word paper for school on machine learning and how it can apply in solving old text-distortion style CAPTCHAs. It was focused on a comparison between the K-nearest neighbours algorithm and the CART decision tree algorithm. If you and others were interested, I could basically do that essay in presentation form. Here's a link if you want to peruse it first and make sure its appropriate for a talk:
[Ross-Evans-EE-PDF.pdf](https://github.com/peidevs/Event_Resources/files/531420/Ross-Evans-EE-PDF.pdf)

If you really want TensorFlow covered I could probably still do it, but I'd estimate it taking me a couple extra months of preparation, and at that point I'm sure somebody else would be better for the job. If I was just to present what was in my essay, I'd be ready by November.

Let me know what you, and the rest of the elders, think.

**Comment by codetojoy** [comment]
Thanks for posting, Ross! Happily, we're currently full for November, but have an opening in Jan/Feb 2017 (December is reserved as a social event). (_Edit:_ I originally put January but let's say either January or February... more later on)

I skimmed the essay... very impressive! With some massaging for our audience (e.g. slightly less academic, with high-level code examples) I think it will be a fine talk indeed. I'd postpone TensorFlow for now but certainly encourage that as a goal.

Please let us know (here or email) if Jan/Feb 2017 works. Thanks again!

**Comment by Qcode** [comment]
Thanks for your response. I'd love to take the opening in January/February, just let me know whichever date is best. I'll make sure to adjust some of the content and include more code examples. Thanks once again for the opportunity.

**Comment by codetojoy** [comment]
Per email convo, this is scheduled for Feb 2017. Thanks!
