### ISSUE TITLE
Talk idea: a presentation on giving technical presentations

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#45]
To help facilitate others giving talks, I offer a talk on giving technical presentations (within the boundaries of my own experience).

A rough outline:
- identify your talk pattern (e.g. lightning talk, conference talk, lunch 'n learn, keynote, etc)
- preparation
  - story arc / elevator pitch
  - practice, practice, practice
  - know time limits
  - dealing with A/V nightmares
- content
  - fancy slides? code?
- dealing with fear
- how to improve
- observing patterns and anti-patterns

**Comment by 2manyprojects2littletime** [comment]
https://github.com/codetojoy/presentations/tree/master/PEI_Devs_Random_Walk
