### ISSUE TITLE
Talk Idea: open forum on ergo(nomics)

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#52]
Someone should facilitate a session (which is really easy, btw) on tools/techniques for ergonomic stuff. e.g. keyboards, mouse, stand-up desks, software to remind you to take a walk, etc.

**Comment by swhalley** [comment]
I have just ordered a Microsoft Sculpt keyboard and mouse. Once I get some time using it, I can do a review with it. Has been rated one of the top ergonomic keyboards since it came out.

**Comment by evanepio** [comment]
Editing the title because I'm not used to the shorthand version of the word.

**Comment by swhalley** [comment]
My Current Ergo Setup

[Microsoft Sculpt Keyboard and mouse](https://www.amazon.ca/Microsoft-Ergonomic-Wireless-Bluetrack-Desktop/dp/B00DUV01SC/ref=sr_1_1?ie=UTF8&qid=1502822143&sr=8-1&keywords=microsoft+sculpt)
[Ikea Bekant Sit/Stand 47" desk](http://www.ikea.com/ca/en/catalog/products/S29022520/)

In the market for 
[Monitor Arm ](http://www.dell.com/en-ca/shop/dell-slim-single-monitor-arm-mssa18/apd/452-bcxi/monitors-flat-screen-lcd-computer-displays)
Chair

**Comment by codetojoy** [comment]
FWIW, my experience:

- [Varidesk 36 ProPlus](https://www.varidesk.com/products/standing-desk-pro-plus?o=Size%3a36+inch%3bColor%3aBlack), at home, which I love.
- Fun fact: standing [doesn't burn](https://www.runnersworld.com/health/do-you-burn-more-calories-at-a-standing-desk) more calories, but can help with back pain and blood sugar.
- I'm right-handed, but have been using mouse with my left-hand for 20 years. My right wrist was starting to act up but it has been a useful, weird experiment.
- In my experience, swimming has been the best form of exercise, bordering on miraculous (e.g. for wrist pain).

**Comment by swhalley** [comment]
**Discussion Topics**
- Chairs, Desks and Monitors
   - Bloodflow from standing
   - proper posture from chair and monitor height
   - Benefit of a monitor arm
- Keyboards, Mice and wireless headsets
- 45min sprints
- Office vs Home Office constraints
- Arms off chairs
- Yoga Matt, Resistance bands, Racquet Balls

**Comment by swhalley** [comment]
Sept 2017 meetup
