### ISSUE TITLE
Talk Idea: JDK 9 and Project Jigsaw

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#55]
JDK 9 is due in March 2017, and a major part of it will be the new module system (aka Project Jigsaw). There are early-access versions available now. This is an excellent topic that would be a winner at Maritime Dev Con.

I'm not necessarily offering to give the talk. If I did, I would need 4-6 weeks notice.

**Comment by codetojoy** [comment]
FYI... JDK 9 has been pushed to July 2017.

**Comment by codetojoy** [comment]
FWIW, I'm speaking on this at Maritime DevCon in June 2017. I could potentially do it again after June, if there's interest.

**Comment by evanepio** [comment]
How's August sound?
