### ISSUE TITLE
review Dojo

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#7]
the Dojo code, insofar as there is any, should be idiomatic

**Comment by evanepio** [comment]
This is idiomatic Dojo. So I guess I close it.

The AttendeeList.js is different in that I'm spoiled with Array.protoype.map, forEach, etc. I like my for loops hidden. Of course in 2015 browser support was spottier for the niceties.

There's no non-Dojoiness about Scooter.
