### ISSUE TITLE
Talk idea: From nothing to something

### ISSUE THREAD

**Issue by microp11** [peidevs/Event_Resources#73]
I would like to talk about wireless communications and what happens under the word "wireless":

- binary demodulation or "from a radio wave to one bit"
- puzzles or "from one bit to data encoding"
- fun or "pirates at sea, oil rigs and submarine cables, storm and hurricanes; honey, please bring back a fish!"

Plus some extras on open and closed source, licensing and all. Personal experiences.

Cheers!

**Comment by evanepio** [comment]
Adding label, as it seems we label talk ideas with "question"

March is looking good for presentations. We'll likely follow up sometime closer and see if you're available.

**Comment by codetojoy** [comment]
I believe this talk was given in APR 2018. Though due to many questions (highly interested audience), we ran out of time. Perhaps we leave this issue open as "part 2" for the talk?

**Comment by microp11** [comment]
Thanks,

 

2nd spot for this week, Thu 14?

How much time would I have?

**Comment by codetojoy** [comment]
Just FYI ... June 14 is fully booked. This is for planning in future MeetUps.

**Comment by microp11** [comment]
Cool, I would welcome the opportunity to continue the presentation anytime.

 

Cheers,

Paul

**Comment by codetojoy** [comment]
@microp11 / Paul:

Would you be interested in giving part 2 of your talk on October 11? 

We can't assume that people saw part 1, but also we don't want to repeat too much. So one suggestion is to summarize the first talk in 20 minutes or so, and then continue from there.

We don't usually do "part 2" but there were a lot of questions as time expired, and the projector situation was not very good (it is better now!)

**Comment by microp11** [comment]
Hi Michael,

 

Thank you for the opportunity. I will have some updates as well.

I just returned from a short vacation. I will check my schedule and let you know by tomorrow Wednesday 26th. 

 

Cheers,

Paul

**Comment by microp11** [comment]
Hi Michael,

 

I can do it. Let me know.

 

Cheers,

Paul

 

From: Paul Maxan <paul@aelogic.com> 
Sent: Tuesday, September 25, 2018 12:06 PM
To: 'peidevs/Event_Resources' <reply@reply.github.com>; 'peidevs/Event_Resources' <Event_Resources@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [peidevs/Event_Resources] Talk idea: From nothing to something (#73)

 

Hi Michael,

 

Thank you for the opportunity. I will have some updates as well.

I just returned from a short vacation. I will check my schedule and let you know by tomorrow Wednesday 26th. 

 

Cheers,

Paul

**Comment by codetojoy** [comment]
Great @microp11 !! Thanks very much ... I'll mark you down for October 11. I will need a brief summary of the talk near October 4, but until then we can use placeholder text and refer to the April 2018 talk.
