### ISSUE TITLE
Talk Idea - Hugo and other stuff

### ISSUE THREAD

**Issue by swhalley** [peidevs/Event_Resources#75]
last year I upgraded PEI Devs site to use Hugo and working on my own brand now. 

There is a wide variety of things I can talk about
- Hugo - General Static site dicsussion. Some of the things I learned and layout of applications.
- TravisCI/AWS - How I use a few things to auto deploy my own site.
- My 3 step approach (manual, Travis, Forestry) to get my app deployed
- PEIDevs deploy/setup

**Comment by swhalley** [comment]
I can do this talk as early as Jan 2018

**Comment by evanepio** [comment]
Adding label because I think that's what we do.

**Comment by evanepio** [comment]
Jan 2018 Meetup
