### ISSUE TITLE
Scooter . Dojo - use Dojo AMD

### ISSUE THREAD

**Issue by codetojoy** [peidevs/Event_Resources#9]
from Evan ... The Dojo devs now encourage using the AMD spec way of using Dojo. Here’s Dojo’s official take at an explanation:

https://dojotoolkit.org/documentation/tutorials/1.7/modules/

**Comment by evanepio** [comment]
God help me if this isn't what I already see in Scooter. I've worked with Dojo for three years, and this looks like AMD-spec Dojo.

Message to my Past Self: you're a dumbass if you thought this wasn't AMD.
